### ISSUE TITLE
the message edit/delete logs can exceed Discord's message length limit

### ISSUE THREAD

**Issue by Ixrec** [Manechat/izzy-moonbot#418]
Not exactly a big deal, but since I saw it several times in the logs:
```sh
03/06/2023 0:53:23
[2023-06-02 23:53:23 ERR] An UnobservedTaskException occured, i.e. one of Izzy's async tasks threw an exception that remained unhandled until the task was GC'd. That usually means the issue was in an event handler rather than a command handler.
03/06/2023 0:53:23
Unobserved Exception Message: Message content is too long, length must be less or equal to 2000. (Parameter 'Content')
03/06/2023 0:53:23
Unobserved Exception Stack:    at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
03/06/2023 0:53:23
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, RequestOptions options, Embed[] embeds, MessageFlags flags)
03/06/2023 0:53:23
   at Izzy_Moonbot.Adapters.SocketTextChannelAdapter.SendMessageAsync(String message, AllowedMentions allowedMentions, MessageComponent components, RequestOptions options, ISticker[] stickers, Embed[] embeds) in /src/Izzy-Moonbot/Adapters/DiscordNetAdapters.cs:line 195
03/06/2023 0:53:23
   at Izzy_Moonbot.EventListeners.MessageListener.ProcessMessageUpdate(String oldContent, IIzzyMessage newMessage, IIzzyMessageChannel channel, IIzzyClient client) in /src/Izzy-Moonbot/EventListeners/MessageListener.cs:line 65
```

**Comment by Ixrec** [comment]
Confirmed I can easily reproduce this by editing a huge message

**Comment by Ixrec** [comment]
Confirmed that deleting a huge message also easily reproduces this, with the same helpfully specific error message as the edit case, unlike #419. So I'm gonna count these as the same issue and #419 we can safely assume was just the recent Discord outage.

```sh
04/06/2023 15:57:44
[2023-06-04 14:57:44 ERR] An UnobservedTaskException occured, i.e. one of Izzy's async tasks threw an exception that remained unhandled until the task was GC'd. That usually means the issue was in an event handler rather than a command handler.
04/06/2023 15:57:44
Unobserved Exception Message: Message content is too long, length must be less or equal to 2000. (Parameter 'Content')
04/06/2023 15:57:44
Unobserved Exception Stack:    at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
04/06/2023 15:57:44
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, RequestOptions options, Embed[] embeds, MessageFlags flags)
04/06/2023 15:57:44
   at Izzy_Moonbot.Adapters.SocketTextChannelAdapter.SendMessageAsync(String message, AllowedMentions allowedMentions, MessageComponent components, RequestOptions options, ISticker[] stickers, Embed[] embeds) in /src/Izzy-Moonbot/Adapters/DiscordNetAdapters.cs:line 195
04/06/2023 15:57:44
   at Izzy_Moonbot.EventListeners.MessageListener.ProcessMessageDelete(UInt64 messageId, IIzzyMessage message, UInt64 channelId, IIzzyMessageChannel channel, IIzzyClient client) in /src/Izzy-Moonbot/EventListeners/MessageListener.cs:line 106
```
