### ISSUE TITLE
timeouts when posting deleted message logs

### ISSUE THREAD

**Issue by Ixrec** [Manechat/izzy-moonbot#419]
```sh
04/06/2023 15:29:26
[2023-06-04 14:29:26 ERR] An UnobservedTaskException occured, i.e. one of Izzy's async tasks threw an exception that remained unhandled until the task was GC'd. That usually means the issue was in an event handler rather than a command handler.
04/06/2023 15:29:26
Unobserved Exception Message: The operation has timed out.
04/06/2023 15:29:26
Unobserved Exception Stack:    at Discord.Net.Queue.RequestBucket.EnterAsync(Int32 id, IRequest request)
04/06/2023 15:29:26
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
04/06/2023 15:29:26
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
04/06/2023 15:29:26
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
04/06/2023 15:29:26
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
04/06/2023 15:29:26
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
04/06/2023 15:29:26
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, RequestOptions options, Embed[] embeds, MessageFlags flags)
04/06/2023 15:29:26
   at Izzy_Moonbot.Adapters.SocketTextChannelAdapter.SendMessageAsync(String message, AllowedMentions allowedMentions, MessageComponent components, RequestOptions options, ISticker[] stickers, Embed[] embeds) in /src/Izzy-Moonbot/Adapters/DiscordNetAdapters.cs:line 195
04/06/2023 15:29:26
   at Izzy_Moonbot.EventListeners.MessageListener.ProcessMessageDelete(UInt64 messageId, IIzzyMessage message, UInt64 channelId, IIzzyMessageChannel channel, IIzzyClient client) in /src/Izzy-Moonbot/EventListeners/MessageListener.cs:line 106
```

These events were several hours removed from the #418 events I saw, so there's probably no direct connection, but I wouldn't be surprised if this one also boils down to posting too much stuff in #bot-logs despite the far vaguer error message.

Due to the vagueness, and the fact that by definition this was caused by a deleted message we failed to generate a log for, we don't have concrete examples of causes, so first step is probably to add a catch block for this to give us more to work with.

**Comment by cloudburstwan** [comment]
This was caused by a [Discord API incident](https://discordstatus.com/incidents/xbmd97zcdj83)

**Comment by Ixrec** [comment]
You're right, I was thrown off by noticing both #418 and this at the same time.
