### ISSUE TITLE
Context actions fire twice

### ISSUE THREAD

**Issue by MercurialPony** [Manechat/izzy-moonbot#555]
![image](https://github.com/Manechat/izzy-moonbot/assets/19710443/f9df6ab3-695a-42b7-b670-970a2ee4a80b)

**Comment by Ixrec** [comment]
```
[2024-01-29 17:44:13 INF] UserCommandHandler received 1172683791488258158 .permanp
[2024-01-29 17:44:13 INF] UserCommandHandler received 1172683791488258158 .permanp
[2024-01-29 17:44:13 ERR] Izzy Moonbot has encountered an error. Logging information...
[2024-01-29 17:44:13 ERR] Message: Cannot respond twice to the same interaction
[2024-01-29 17:44:13 ERR] Source: Discord.Net.WebSocket
[2024-01-29 17:44:13 ERR] HResult: -2146233079
[2024-01-29 17:44:13 ERR] Stack trace:    at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Izzy_Moonbot.Worker.UserCommandHandler(SocketUserCommand command) in /src/Izzy-Moonbot/Worker.cs:line 502
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
[2024-01-29 17:44:13 INF] A UserCommandExecuted handler has thrown an unhandled exception.
```

**Comment by Ixrec** [comment]
Simply restarting Izzy got rid of this duplication. I believe this means

https://github.com/Manechat/izzy-moonbot/blob/5991f69dd083de90f42ad481d59154d66d3c45bf/Izzy-Moonbot/Worker.cs#L226

got executed twice during her last... "session of uptime"(?). That happens in `ReadyEvent()`, and...

https://github.com/Manechat/izzy-moonbot/blob/5991f69dd083de90f42ad481d59154d66d3c45bf/Izzy-Moonbot/Worker.cs#L93

so I can only assume Discord sent her 2 ready events for some reason???

No idea if we can or should do anything about this. That's all I'm gonna do for now.

**Comment by MercurialPony** [comment]
Huh, weird. That means everything else inside ReadyEvent was also registered and executed twice?
I guess we'll have to investigate closer if it happens again

**Comment by Ixrec** [comment]
Happened again today. A restart fixed it again.
